version: '2.1'

services:

  bitcoin:
    image: ruimarinho/bitcoin-core:0.16-alpine
    container_name: bitcoin
    ports:
      - 18443:18443
    command: -regtest=1 -printtoconsole -rpcallowip=0.0.0.0/0 -rpcuser=test -rpcpassword=test

  litecoin:
    image: uphold/litecoin-core:0.15.1
    container_name: litecoin
    ports:
      - 19332:19332
    command: -regtest=1 -printtoconsole -rpcallowip=0.0.0.0/0 -rpcuser=test -rpcpassword=test

  bitcoin-cash:
    image: uphold/bitcoin-abc:0.17.1-alpine
    container_name: bitcoin-cash
    ports:
      - 18332:18332
    command: -regtest=1 -printtoconsole -rpcallowip=0.0.0.0/0 -rpcuser=test -rpcpassword=test

  ethereum:
    image: trufflesuite/ganache-cli:v6.1.6
    container_name: ethereum
    ports:
      - 8545:8545
    command: --hostname 0.0.0.0 --account="0x869844d42d74171d1c5e71ecd8964118e68f610af94047fd1e98afb4df1c5e1b,1000000000000000000000000"
