version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: pyenv install 3.6.3 && pyenv global 3.6.3
      - run: pip install docker-compose
      - run: docker-compose up -d 
      - run:
          name: install
          command: |
            pip3 install -r dev/requirements.txt
            pip3 install -r dev/requirements-dev.txt
      - run:
          name: flake8
          command: flake8
      - run:
          name: docker containers
          command: sudo docker ps -a
      - run:
          name: test
          command: pytest --cov
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)      
