version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: pyenv install 3.6.3 && pyenv global 3.6.3
      - run: pip3 install docker-compose
      - run:
          name: Run test nodes
          command: make blockchains
      - run: sleep 5
      - run:
          name: Generate coins
          command: make coins
      - run:
          name: Install Python dependencies
          command: ./dev/install.sh
      - run:
          name: test
          command: make test
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)
  deploy-release:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: install-dev
          command: sudo ./dev/install-dev.sh
      - run:
          name: validate version
          command: agilekit git validate
      - run:
          name: build bundles
          command: sudo make bundles
      - run:
          name: upload release
          command: twine upload dist/* --username lsbardel --password $PYPI_PASSWORD
      - run:
          name: create tag
          command: agilekit git release --yes

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-release:
          requires:
            - build
          filters:
            branches:
              only: deploy
            tags:
              ignore: /.*/
