version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo pip install docker-compose
      - run: sudo docker-compose up -d
      - run:
          name: install
          command: sudo ./dev/install.sh
      - run:
          name: flake8
          command: flake8
      - run:
          name: test
          command: pytest --cov
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)      
